name: PrimerAction
on: push

jobs:
    lamine:
        runs-on: ubuntu-latest
        steps:
            - name: primera accion
                uses: actions/checkout@v3
            - run: echo "Hola Mundo"